name: fintrack_app
description: Aplikasi catatan keuangan Fintrack (Flutter + Laravel API).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.4.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # Tambahan package ikon di sini

flutter:
  uses-material-design: true
  assets:
    - assets/images/LogoFintrack.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/LogoFintrack.png
  
  android_12:
    color: "#ffffff"
    image: assets/images/LogoFintrack.png
    
  android_gravity: center
  ios_content_mode: center

# 👈 Konfigurasi untuk generate ikon aplikasi otomatis
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"